export const FETCH_AVAILABLE_STORES_SUCCESS = 'store/FETCH_AVAILABLE_STORES_SUCCESS';
export const FETCH_AVAILABLE_STORES_START = 'store/FETCH_AVAILABLE_STORES_START';
export const FETCH_AVAILABLE_STORES_ERROR = 'store/FETCH_AVAILABLE_STORES_ERROR';
export const SELECTED_STORE_CHANGE = 'store/SELECTED_STORE_CHANGE';
