export const SET_CHECKOUT_DATA = 'checkout/SET_CHECKOUT_DATA';
export const CREATE_ORDER_START = 'checkout/CREATE_ORDER_START';
export const CREATE_ORDER_SUCCESS = 'checkout/CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_ERROR = 'checkout/CREATE_ORDER_ERROR';
export const USE_SAVED_PAYMENT_METHOD = 'checkout/USE_SAVED_PAYMENT_METHOD';
export const USE_NEW_PAYMENT_METHOD = 'checkout/USE_NEW_PAYMENT_METHOD';
export const TOGGLE_SAVE_PAYMENT_METHOD_CONTROL = 'checkout/TOGGLE_SAVE_PAYMENT_METHOD_CONTROL';
export const RESET_CHECKOUT_STATE = 'checkout/RESET_CHECKOUT_STATE';
