export const PRODUCT_FETCH_START = 'barcode/PRODUCT_FETCH_START';
export const PRODUCT_FETCH_SUCCESS = 'barcode/PRODUCT_FETCH_SUCCESS';
export const PRODUCT_FETCH_ERROR = 'barcode/PRODUCT_FETCH_ERROR';
export const REMOVE_SCANNED_PRODUCT = 'barcode/REMOVE_SCANNED_PRODUCT';
