export const FETCH_USER_DATA_START = 'user/FETCH_USER_DATA_START';
export const FETCH_USER_DATA_SUCCESS = 'user/FETCH_USER_DATA_SUCCESS';
export const FETCH_USER_DATA_ERROR = 'user/FETCH_USER_DATA_ERROR';

export const ADD_PAYMENT_METHOD_START = 'user/ADD_PAYMENT_METHOD_START';
export const ADD_PAYMENT_METHOD_SUCCESS = 'user/ADD_PAYMENT_METHOD_SUCCESS';
export const ADD_PAYMENT_METHOD_ERROR = 'user/ADD_PAYMENT_METHOD_ERROR';
