export const ADD_TO_BASKET_REQUEST_START = 'basket/ADD_TO_BASKET_REQUEST_START';
export const ADD_TO_BASKET_REQUEST_SUCCESS = 'basket/ADD_TO_BASKET_REQUEST_SUCCESS';
export const ADD_TO_BASKET_REQUEST_ERROR = 'basket/ADD_TO_BASKET_REQUEST_ERROR';

export const CHANGE_BASKET_ITEM_QUANTITY_REQUEST_START = 'basket/CHANGE_BASKET_ITEM_QUANTITY_REQUEST_START';
export const CHANGE_BASKET_ITEM_QUANTITY_REQUEST_SUCCESS = 'basket/CHANGE_BASKET_ITEM_QUANTITY_REQUEST_SUCCESS';
export const CHANGE_BASKET_ITEM_QUANTITY_REQUEST_ERROR = 'basket/CHANGE_BASKET_ITEM_QUANTITY_REQUEST_ERROR';

export const REMOVE_BASKET_ITEM_REQUEST_START = 'basket/REMOVE_BASKET_ITEM_REQUEST_START';
export const REMOVE_BASKET_ITEM_REQUEST_SUCCESS = 'basket/REMOVE_BASKET_ITEM_REQUEST_SUCCESS';
export const REMOVE_BASKET_ITEM_REQUEST_ERROR = 'basket/REMOVE_BASKET_ITEM_REQUEST_ERROR';

export const CREATE_BASKET_SUCCESS = 'basket/CREATE_BASKET_SUCCESS';

export const FETCH_BASKET_START = 'basket/FETCH_BASKET_START';
export const FETCH_BASKET_SUCCESS = 'basket/FETCH_BASKET_SUCCESS';
export const FETCH_BASKET_ERROR = 'basket/FETCH_BASKET_ERROR';

export const DELETE_BASKET = 'basket/DELETE_BASKET'

