export const CATEGORIES_FETCH_START = 'categories/CATEGORIES_FETCH_START';
export const CATEGORIES_FETCH_SUCCESS = 'categories/CATEGORIES_FETCH_SUCCESS';
export const CATEGORIES_FETCH_ERROR = 'categories/CATEGORIES_FETCH_ERROR';
export const SET_MAIN_CATEGORY = 'categories/SET_MAIN_CATEGORY';
