export const FETCH_RECEIPTS_START = 'receipts/FETCH_RECEIPTS_START';
export const FETCH_RECEIPTS_SUCCESS = 'receipts/FETCH_RECEIPTS_SUCCESS';
export const FETCH_RECEIPTS_ERROR = 'receipts/FETCH_RECEIPTS_ERROR';
